### PR TITLE
DL: Feature/create member list

### PR DESCRIPTION
**Pull request by dwleung**
Created member list with the following functionality: 
1. Render list of members from Firestore firebase-data-p3
2. Scroll with fadeout at the bottom
3. Checkboxes: 
a) Toggling the checkbox in the header will add or remove all emails from the array membersSelected
b) Toggling the individual checkboxes will add or remove individual emails from array membersSelected
c) There is a 'test' section at the top so we can see which member emails have been added/removed from the array

### CODE REVIEW

**Review by andrewalson — APPROVED** [review]
Great work Danielle :) leaving it open for Tomas/Taylor/Sheena to review & merge.

**Review by taylorsabbag — CHANGES_REQUESTED** [review]
Starting up the dev server supplies an error suggesting that the seconds property on user.lastLogin is undefined. In addition, the member.js file is unnecessary as we moved over to "user" terminology due to the naming of the "Users" table in Firebase. There are also conflicts that need to be resolved with main. You may need to pull from main again before re-committing.

Great work styling the page!

**Comment by dwleung** [comment]
Pulled from main and resolved conflicts - Moved search input and Members count to the same container.

**Review by tomas-tank3ngine — APPROVED** [review]
Works! just make sure that your .env variables are set up to the memberdataP3 firebase.

**Pull request merged**
